---
name: Add `sponsors` labels
on: # yamllint disable-line rule:truthy
  pull_request:
    types: [opened]
  issues:
    types: [opened]

jobs:
  is-sponsor-label:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/is-sponsor-label-action@565f3cb67b3518a8aae36c3f0bce9e8513430e84 # v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
