---
name: Synchronize labels
on: # yamllint disable-line rule:truthy
  repository_dispatch:
    types: [sync-labels]
  schedule:
    - cron: 0 3 * * 0,3
  workflow_dispatch:

jobs:
  sync-labels:
    name: Synchronize org. '{{ github.organization }}' labels
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@24cb9080177205b6e8c946b17badbe402adc938f # v3.4.0
        with:
          repository: belug-apps/.github
      - uses: micnncim/action-label-syncer@3abd5ab72fda571e69fffd97bd4e0033dd5f495c # tag=v1.3.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
